#!/bin/bash
sbatch slurm/wai_processing.sh 0 32
sbatch slurm/wai_processing.sh 1 32
sbatch slurm/wai_processing.sh 2 32
sbatch slurm/wai_processing.sh 3 32
sbatch slurm/wai_processing.sh 4 32
sbatch slurm/wai_processing.sh 5 32
sbatch slurm/wai_processing.sh 6 32
sbatch slurm/wai_processing.sh 7 32
sbatch slurm/wai_processing.sh 8 32
sbatch slurm/wai_processing.sh 9 32
sbatch slurm/wai_processing.sh 10 32
sbatch slurm/wai_processing.sh 11 32
sbatch slurm/wai_processing.sh 12 32
sbatch slurm/wai_processing.sh 13 32
sbatch slurm/wai_processing.sh 14 32
sbatch slurm/wai_processing.sh 15 32
sbatch slurm/wai_processing.sh 16 32
sbatch slurm/wai_processing.sh 17 32
sbatch slurm/wai_processing.sh 18 32
sbatch slurm/wai_processing.sh 19 32
sbatch slurm/wai_processing.sh 20 32
sbatch slurm/wai_processing.sh 21 32
sbatch slurm/wai_processing.sh 22 32
sbatch slurm/wai_processing.sh 23 32
sbatch slurm/wai_processing.sh 24 32
sbatch slurm/wai_processing.sh 25 32
sbatch slurm/wai_processing.sh 26 32
sbatch slurm/wai_processing.sh 27 32
sbatch slurm/wai_processing.sh 28 32
sbatch slurm/wai_processing.sh 29 32
sbatch slurm/wai_processing.sh 30 32
sbatch slurm/wai_processing.sh 31 32